lots of updates

diff --git a/pack/plugins/start/junegunn-fzf/install b/pack/plugins/start/junegunn-fzf/install
--- a/pack/plugins/start/junegunn-fzf/install
+++ b/pack/plugins/start/junegunn-fzf/install
@@ -2,9 +2,7 @@
 
 set -u
 
-[[ "$@" =~ --pre ]] && version=0.15.9 pre=1 ||
-                       version=0.15.9 pre=0
-
+version=0.16.4
 auto_completion=
 key_bindings=
 update_config=2
@@ -48,7 +46,7 @@ for opt in "$@"; do
     --no-update-rc)    update_config=0   ;;
     --32)              binary_arch=386   ;;
     --64)              binary_arch=amd64 ;;
-    --bin|--pre)       ;;
+    --bin)             ;;
     *)
       echo "unknown option: $opt"
       help
@@ -90,17 +88,6 @@ check_binary() {
   return 1
 }
 
-symlink() {
-  echo "  - Creating symlink: bin/$1 -> bin/fzf"
-  (cd "$fzf_base"/bin &&
-   rm -f fzf &&
-   ln -sf $1 fzf)
-  if [ $? -ne 0 ]; then
-    binary_error="Failed to create symlink"
-    return 1
-  fi
-}
-
 link_fzf_in_path() {
   if which_fzf="$(command -v fzf)"; then
     echo "  - Found in \$PATH"
@@ -121,13 +108,10 @@ try_wget() {
 
 download() {
   echo "Downloading bin/fzf ..."
-  if [ $pre = 0 ]; then
+  if [[ ! "$version" =~ alpha ]]; then
     if [ -x "$fzf_base"/bin/fzf ]; then
       echo "  - Already exists"
       check_binary && return
-    fi
-    if [ -x "$fzf_base"/bin/$1 ]; then
-      symlink $1 && check_binary && return
     fi
     link_fzf_in_path && return
   fi
@@ -137,7 +121,10 @@ download() {
     return
   fi
 
-  local url=https://github.com/junegunn/fzf-bin/releases/download/$version/${1}.tgz
+  local url
+  [[ "$version" =~ alpha ]] &&
+    url=https://github.com/junegunn/fzf-bin/releases/download/alpha/${1}.tgz ||
+    url=https://github.com/junegunn/fzf-bin/releases/download/$version/${1}.tgz
   set -o pipefail
   if ! (try_curl $url || try_wget $url); then
     set +o pipefail
@@ -146,12 +133,12 @@ download() {
   fi
   set +o pipefail
 
-  if [ ! -f $1 ]; then
+  if [ ! -f fzf ]; then
     binary_error="Failed to download ${1}"
     return
   fi
 
-  chmod +x $1 && symlink $1 && check_binary
+  chmod +x fzf && check_binary
 }
 
 # Try to download binary executable
@@ -159,83 +146,20 @@ archi=$(uname -sm)
 binary_available=1
 binary_error=""
 case "$archi" in
-  Darwin\ x86_64) download fzf-$version-darwin_${binary_arch:-amd64} ;;
-  Darwin\ i*86)   download fzf-$version-darwin_${binary_arch:-386}   ;;
-  Linux\ x86_64)  download fzf-$version-linux_${binary_arch:-amd64}  ;;
-  Linux\ i*86)    download fzf-$version-linux_${binary_arch:-386}    ;;
-  *)              binary_available=0 binary_error=1  ;;
+  Darwin\ *64)   download fzf-$version-darwin_${binary_arch:-amd64}  ;;
+  Darwin\ *86)   download fzf-$version-darwin_${binary_arch:-386}    ;;
+  Linux\ *64)    download fzf-$version-linux_${binary_arch:-amd64}   ;;
+  Linux\ *86)    download fzf-$version-linux_${binary_arch:-386}     ;;
+  Linux\ armv5*) download fzf-$version-linux_${binary_arch:-arm5}    ;;
+  Linux\ armv6*) download fzf-$version-linux_${binary_arch:-arm6}    ;;
+  Linux\ armv7*) download fzf-$version-linux_${binary_arch:-arm7}    ;;
+  Linux\ armv8*) download fzf-$version-linux_${binary_arch:-arm8}    ;;
+  FreeBSD\ *64)  download fzf-$version-freebsd_${binary_arch:-amd64} ;;
+  FreeBSD\ *86)  download fzf-$version-freebsd_${binary_arch:-386}   ;;
+  OpenBSD\ *64)  download fzf-$version-openbsd_${binary_arch:-amd64} ;;
+  OpenBSD\ *86)  download fzf-$version-openbsd_${binary_arch:-386}   ;;
+  *)             binary_available=0 binary_error=1 ;;
 esac
-
-install_ruby_fzf() {
-  if [ -z "$allow_legacy" ]; then
-    ask "Do you want to install legacy Ruby version instead?" && exit 1
-  fi
-  echo "Installing legacy Ruby version ..."
-
-  # ruby executable
-  echo -n "Checking Ruby executable ... "
-  ruby=$(command -v ruby)
-  if [ $? -ne 0 ]; then
-    echo "ruby executable not found !!!"
-    exit 1
-  fi
-
-  # System ruby is preferred
-  system_ruby=/usr/bin/ruby
-  if [ -x $system_ruby ] && [ $system_ruby != "$ruby" ]; then
-    $system_ruby --disable-gems -rcurses -e0 2> /dev/null
-    [ $? -eq 0 ] && ruby=$system_ruby
-  fi
-
-  echo "OK ($ruby)"
-
-  # Curses-support
-  echo -n "Checking Curses support ... "
-  "$ruby" -rcurses -e0 2> /dev/null
-  if [ $? -eq 0 ]; then
-    echo "OK"
-  else
-    echo "Not found"
-    echo "Installing 'curses' gem ... "
-    if (( EUID )); then
-      /usr/bin/env gem install curses --user-install
-    else
-      /usr/bin/env gem install curses
-    fi
-    if [ $? -ne 0 ]; then
-      echo
-      echo "Failed to install 'curses' gem."
-      if [[ $(uname -r) =~ 'ARCH' ]]; then
-        echo "Make sure that base-devel package group is installed."
-      fi
-      exit 1
-    fi
-  fi
-
-  # Ruby version
-  echo -n "Checking Ruby version ... "
-  "$ruby" -e 'exit RUBY_VERSION >= "1.9"'
-  if [ $? -eq 0 ]; then
-    echo ">= 1.9"
-    "$ruby" --disable-gems -rcurses -e0 2> /dev/null
-    if [ $? -eq 0 ]; then
-      fzf_cmd="$ruby --disable-gems $fzf_base/fzf"
-    else
-      fzf_cmd="$ruby $fzf_base/fzf"
-    fi
-  else
-    echo "< 1.9"
-    fzf_cmd="$ruby $fzf_base/fzf"
-  fi
-
-  # Create fzf script
-  echo -n "Creating wrapper script for fzf ... "
-  rm -f "$fzf_base"/bin/fzf
-  echo "#!/bin/sh" > "$fzf_base"/bin/fzf
-  echo "$fzf_cmd \"\$@\"" >> "$fzf_base"/bin/fzf
-  chmod +x "$fzf_base"/bin/fzf
-  echo "OK"
-}
 
 cd "$fzf_base"
 if [ -n "$binary_error" ]; then
@@ -254,12 +178,12 @@ if [ -n "$binary_error" ]; then
       echo "OK"
       cp "$GOPATH/bin/fzf" "$fzf_base/bin/"
     else
-      echo "Failed to build binary ..."
-      install_ruby_fzf
+      echo "Failed to build binary. Installation failed."
+      exit 1
     fi
   else
-    echo "go executable not found. Cannot build binary ..."
-    install_ruby_fzf
+    echo "go executable not found. Installation failed."
+    exit 1
   fi
 fi
 
